checksource/urls.py
from django.urls import path,re_path,include
from . import views

urlpatterns = [
    #主页
    path('', views.index, name='index'),
    #所有数据
    path('allproblems/', views.allproblems, name='allproblems'),
    #添加新数据
    path('newproblem/', views.newproblem, name='newproblem'),
    #编辑数据
    path('editproblem/(?P<problem_id>\d+)/', views.editproblem, name='editproblem'),
    #查询条件输入
    path('inquireinput/',views.inquireinput,name='inquireinput'),
    #查询条件输出
    path('inquireresult/&&(?P<checkwhenstart>\.*?)&&(?P<checkwhenend>\.*?)&&(?P<checkdepartment>\.*?)&&(?P<checkway>\.*?)&&(?P<checkwho>\.*?)&&(?P<problemdetail>\.*?)&&(?P<problemtype>\.*?)&&(?P<problemsolve>\.*?)&&(?P<whoresponsible>\.*?)&&(?P<departmentincharge>\.*?)&&(?P<problemdepartment>\.*?)&&(?P<departmentwho>\.*?)&&(?P<problemteam>\.*?)&&(?P<problemwho>\.*?)&&(?P<problemreason>\.*?)&&(?P<projecttype>\.*?)&&(?P<closewho>\.*?)&&(?P<ifdone>\.*?)&&/',views.inquireresult,name='inquireresult'),
    
    #上传图片
    path('upload/(?P<problem_id>\d+)/',views.upload,name='upload'),
    #删除图片
    path('/deleteimg/(?P<img_id>\d+)/',views.deleteimg,name= 'deleteimg'),
    #根据主键ID查询
    path('problemid/(?P<p_id>\d+)/', views.problemid, name='problemid'),
    #查询列表修改某条数据，与problemid基本一致，只是多了返回查询的列表
    path('problemidcheck/(?P<p_id>\d+)&&(?P<checkwhenstart>\.*?)&&(?P<checkwhenend>\.*?)&&(?P<checkdepartment>\.*?)&&(?P<checkway>\.*?)&&(?P<checkwho>\.*?)&&(?P<problemdetail>\.*?)&&(?P<problemtype>\.*?)&&(?P<problemsolve>\.*?)&&(?P<whoresponsible>\.*?)&&(?P<departmentincharge>\.*?)&&(?P<problemdepartment>\.*?)&&(?P<departmentwho>\.*?)&&(?P<problemteam>\.*?)&&(?P<problemwho>\.*?)&&(?P<problemreason>\.*?)&&(?P<projecttype>\.*?)&&(?P<closewho>\.*?)&&(?P<ifdone>\.*?)&&/', views.problemidcheck, name='problemidcheck'),
    #编辑数据,根据查询后点击的id和查询参数再返回
    path('editproblemcheck/(?P<p_id>\d+)&&(?P<checkwhenstart>\.*?)&&(?P<checkwhenend>\.*?)&&(?P<checkdepartment>\.*?)&&(?P<checkway>\.*?)&&(?P<checkwho>\.*?)&&(?P<problemdetail>\.*?)&&(?P<problemtype>\.*?)&&(?P<problemsolve>\.*?)&&(?P<whoresponsible>\.*?)&&(?P<departmentincharge>\.*?)&&(?P<problemdepartment>\.*?)&&(?P<departmentwho>\.*?)&&(?P<problemteam>\.*?)&&(?P<problemwho>\.*?)&&(?P<problemreason>\.*?)&&(?P<projecttype>\.*?)&&(?P<closewho>\.*?)&&(?P<ifdone>\.*?)&&/', views.editproblemcheck, name='editproblemcheck'),
    #上传图片,根据查询后点击的id和查询参数再返回
    path('uploadcheck/(?P<p_id>\d+)&&(?P<checkwhenstart>\.*?)&&(?P<checkwhenend>\.*?)&&(?P<checkdepartment>\.*?)&&(?P<checkway>\.*?)&&(?P<checkwho>\.*?)&&(?P<problemdetail>\.*?)&&(?P<problemtype>\.*?)&&(?P<problemsolve>\.*?)&&(?P<whoresponsible>\.*?)&&(?P<departmentincharge>\.*?)&&(?P<problemdepartment>\.*?)&&(?P<departmentwho>\.*?)&&(?P<problemteam>\.*?)&&(?P<problemwho>\.*?)&&(?P<problemreason>\.*?)&&(?P<projecttype>\.*?)&&(?P<closewho>\.*?)&&(?P<ifdone>\.*?)&&/', views.uploadcheck, name='uploadcheck'),
    #整改完毕确认返回查询列表
    path('problemdoneconfirm/(?P<p_id>\d+)&&(?P<checkwhenstart>\.*?)&&(?P<checkwhenend>\.*?)&&(?P<checkdepartment>\.*?)&&(?P<checkway>\.*?)&&(?P<checkwho>\.*?)&&(?P<problemdetail>\.*?)&&(?P<problemtype>\.*?)&&(?P<problemsolve>\.*?)&&(?P<whoresponsible>\.*?)&&(?P<departmentincharge>\.*?)&&(?P<problemdepartment>\.*?)&&(?P<departmentwho>\.*?)&&(?P<problemteam>\.*?)&&(?P<problemwho>\.*?)&&(?P<problemreason>\.*?)&&(?P<projecttype>\.*?)&&(?P<closewho>\.*?)&&(?P<ifdone>\.*?)&&/',views.problemdoneconfirm,name='problemdoneconfirm'),
    #整改完毕确认
    path('problemdoneconfirmnew/(?P<p_id>\d+)/',views.problemdoneconfirmnew,name='problemdoneconfirmnew'),
    #删除图片返回列表
    path('deleteproblemcheck/(?P<p_id>\d+)&&(?P<checkwhenstart>\.*?)&&(?P<checkwhenend>\.*?)&&(?P<checkdepartment>\.*?)&&(?P<checkway>\.*?)&&(?P<checkwho>\.*?)&&(?P<problemdetail>\.*?)&&(?P<problemtype>\.*?)&&(?P<problemsolve>\.*?)&&(?P<whoresponsible>\.*?)&&(?P<departmentincharge>\.*?)&&(?P<problemdepartment>\.*?)&&(?P<departmentwho>\.*?)&&(?P<problemteam>\.*?)&&(?P<problemwho>\.*?)&&(?P<problemreason>\.*?)&&(?P<projecttype>\.*?)&&(?P<closewho>\.*?)&&(?P<ifdone>\.*?)&&/',views.deleteproblemcheck,name='deleteproblemcheck'),
    #删除图片
    path('deleteproblem/(?P<p_id>\d+)/',views.deleteproblem,name='deleteproblem'),
    
    
    
]

dangersourcrbywangqi/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include(('checksource.urls','checksource'),namespace='checksource')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checksource/forms.py
from django import forms
from .models import Checkproblem,Inquireproblem,ImgProblem
from bootstrap_datepicker_plus import DateTimePickerInput

checkwaylist =(('', ''),('现场检查', '现场检查'),('录像筛查', '录像筛查'),('记录及印证式提问', '记录及印证式提问'))
protypelist = (('', ''),('违章', '违章'),('违规', '违规'),('作风', '作风'))
ifdonelist = ((None,'所有'),(True,'是' ),(False,'否' ))
class CheckproblemForm(forms.ModelForm):  #新增检查的表单
	class Meta:
		model = Checkproblem   #根据哪个模型创造的表单
		   #表单中包含的字段
		exclude = ['ifdone']
		labels = {'checkwhen':"检查日期",'checkdepartment': '检查部门','checkway':'检查方式','checkwho':'检查者','problemdetail':'问题描述','problemtype':'问题分类','problemsolve':'整改措施','whoresponsible':'部分管责任人','departmentincharge':'主控部门','problemdepartment':'责任部门','departmentwho':'部门负责人','problemteam':'责任班组','problemwho':'具体责任人','problemreason':'本部门原因分析','closedate':'预计关闭日期','projecttype':'项目分类','closewho':'关闭批准人','somethingelse':'备注',}
		widgets = {'checkwhen':DateTimePickerInput(
		options={"format": "YYYY-MM-DD","locale":"zh-cn",}),
		'checkway':forms.Select(choices=checkwaylist),
		'problemtype':forms.Select(choices=protypelist),
		'closedate':DateTimePickerInput(
		options={"format": "YYYY-MM-DD","locale":"zh-cn",}),
		'problemdetail': forms.Textarea(attrs={'cols': 40,'rows':3}),#
		'problemsolve': forms.Textarea(),#attrs={'cols': 40,'rows':3}
		'problemreason': forms.Textarea(),#attrs={'cols': 40,'rows':3}
		}
		
class InquireForm1(forms.Form):		  #查询具体条件的表单
	datestart = forms.DateField(widget=DateTimePickerInput(options={
	"format": "YYYY-MM-DD", # moment date-time format
	"showClose": False,
	"showClear": False,
	"showTodayButton": False,
	"locale":"zh-cn",
	}),label='检查起始日期')
	
	dateend = forms.DateField(widget=DateTimePickerInput(options={
	"format": "YYYY-MM-DD", # moment date-time format
	"showClose": False,
	"showClear": False,
	"showTodayButton": False,
	"locale":"zh-cn",
	}),label='检查终止日期')
	
	checkdepartment = forms.CharField(label='检查部门')
	checkway = forms.CharField(max_length=10,widget=forms.widgets.Select(choices=checkwaylist),label='检查方式')
	problemcontain = forms.CharField(label='问题包含')

class InquireForm(forms.ModelForm):  #新增检查的表单
	class Meta:
		model = Inquireproblem   #根据哪个模型创造的表单
		   #表单中包含的字段
		exclude = ['somethingelse','closedate']
		labels = {'checkwhenstart':"起始日期",'checkwhenend':"终止日期",'checkdepartment': '检查部门','checkway':'检查方式','checkwho':'检查者','problemdetail':'问题描述包含','problemtype':'问题分类','problemsolve':'整改措施包含','whoresponsible':'部分管责任人','departmentincharge':'主控部门','problemdepartment':'责任部门','departmentwho':'部门负责人','problemteam':'责任班组','problemwho':'具体责任人','problemreason':'本部门原因分析','closedate':'预计关闭日期','projecttype':'项目分类','closewho':'关闭批准人','ifdone':'是否已整改','somethingelse':'备注',}
		widgets = {'checkwhenstart':DateTimePickerInput(
		options={"format": "YYYY-MM-DD","locale":"zh-cn",}),
		'checkwhenend':DateTimePickerInput(
		options={"format": "YYYY-MM-DD","locale":"zh-cn",}),
		'checkway':forms.Select(choices=checkwaylist),
		'problemtype':forms.Select(choices=protypelist),
		'ifdone':forms.Select(choices=ifdonelist),
		'closedate':DateTimePickerInput(
		options={"format": "YYYY-MM-DD","locale":"zh-cn",}),
		}
		
class ImgProblemForm(forms.ModelForm):
	class Meta:
		model = ImgProblem
		fields = {'img'}		

checksource/views.py
from django.shortcuts import render
from checksource.models import Checkproblem,ImgProblem
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import CheckproblemForm,InquireForm,ImgProblemForm

# Create your views here.
def index(request):
	"""主页"""
	return render(request, 'checksource/index.html')
	
def	allproblems(request):
	"""列出所有检查的问题"""
	problems = Checkproblem.objects.order_by('-checkwhen')
	i = set()
	for pp in problems:
		for imgs in pp.imgproblem_set.all():
			i.add(imgs)
	context = {'problems': problems,'imgproblem':i}
	return render(request, 'checksource/allproblems.html', context)
	
def newproblem(request):
	"""添加一个新问题"""
	if request.method != 'POST':
		# 未提交数据：创建一个新表单
		form = CheckproblemForm()
		context = {'form': form}
		return render(request, 'checksource/newproblem.html', context)
	else:
		# POST提交的数据,对数据进行处理
		form = CheckproblemForm(request.POST)
		if form.is_valid():
			p = Checkproblem()
			for key,value in request.POST.items():
				if key =='checkwhen':
					p.checkwhen = value
				elif key =='checkdepartment':
					p.checkdepartment = value	
				elif key =='checkway':
					p.checkway = value
				elif key =='checkwho':
					p.checkwho = value
				elif key =='problemdetail':
					p.problemdetail = value
				elif key =='problemtype':
					p.problemtype = value
				elif key =='problemsolve':
					p.problemsolve = value
				elif key =='whoresponsible':
					p.whoresponsible = value
				elif key =='problemdepartment':
					p.problemdepartment = value
				elif key =='departmentwho':
					p.departmentwho = value
				elif key =='problemteam':
					p.problemteam = value
				elif key =='problemwho':
					p.problemwho = value
				elif key =='problemreason':
					p.problemreason = value
				elif key =='closedate':
					p.closedatet = value
				elif key =='ifdone':
					p.ifdone = value
				elif key =='projecttype':
					p.projecttype = value
				elif key =='closewho':
					p.closewho = value
				elif key =='somethingelse':
					p.somethingelse = value
				elif key =='checkdepartment':
					p.checkdepartment = value
			p.save()
			return HttpResponseRedirect(reverse('checksource:upload',args=[p.id]))
			
def editproblem(request,problem_id):
	"""编辑问题的内容"""
	next = request.GET.get('next', '')
	problem = Checkproblem.objects.get(id=problem_id)
	if request.method != 'POST':
		form = CheckproblemForm(instance=problem)
		context = {'problem':problem,'form': form}
		return render(request, 'checksource/editproblem.html', context)
	else:
		form = CheckproblemForm(instance=problem, data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('checksource:problemid',args=[problem_id]))
			#return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
			
	

def inquireinput(request):
	"""查询具体条件的检查"""
	pdic = ['checkwhenstart','checkwhenend','checkdepartment','checkway','checkwho','problemdetail','problemtype','problemsolve','whoresponsible','departmentincharge','problemdepartment','departmentwho','problemteam','problemwho','problemreason','projecttype','closewho','ifdone']
	paramdic = {}
	if request.method!='POST':
		form = InquireForm()
		return render(request,'checksource/inquireinput.html',{'form':form})
	else:
		form = InquireForm(data=request.POST)
		if form.is_valid():
			for key,value in request.POST.items():
				if key in pdic:
					if not value:
						if key == 'checkwhenstart':
							paramdic[key] = '2019-01-01'
						elif key == 'checkwhenend':
							paramdic[key] = '2119-12-31'
						else:
							paramdic[key]='all'				
					else:
						paramdic[key]= value			
				else:
					continue		
			
			return HttpResponseRedirect(reverse('checksource:inquireresult',kwargs=paramdic))
					
def inquireresult(request,**kwargs):
	
	"""查询具体条件的检查"""
	i = set()
	problemwithpicid = set()
	problems = Checkproblem.objects.all()
	for key,value in kwargs.items():
		if key!='checkwhenstart' and key!='checkwhenend':
			if value == 'all':
				continue
			elif key == 'problemdetail':
				problems = problems.filter(problemdetail__icontains=value)
			elif key == 'problemsolve':
				problems = problems.filter(problemsolve__icontains=value)
			elif key == 'problemreason':
				problems = problems.filter(problemreason__icontains=value)		
			else:
				condition = {key:value}
				problems = problems.filter(**condition).order_by('checkwhen')
		else:
			continue		
	problems = problems.filter(checkwhen__range=(kwargs['checkwhenstart'],kwargs['checkwhenend'])).order_by('-checkwhen')				
	for pp in problems:
		if pp.imgproblem_set.all():
			problemwithpicid.add(pp.id)
		for imgs in pp.imgproblem_set.all():
			i.add(imgs)
	 
	
	context = {'problems':problems,'imgproblem':i,'paramdic':kwargs,'problemwithpicid':problemwithpicid}	
	return render(request, 'checksource/inquireresult.html', context)		
		
		
		


	
def upload(request,problem_id):
	"""上传问题的图片"""
	next=request.GET.get('next','/')
	problem = Checkproblem.objects.get(id=problem_id)
	if request.method != 'POST':
		#form = ImgProblemForm()
		#context = {'form':form,'problem':problem}
		return render(request,'checksource/upload.html')
	else:
		files = request.FILES.getlist('img',None)
		for f in files:
			form = ImgProblem(img = f)
			form.Checkproblem = problem
			form.save()
		#return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))	
		return HttpResponseRedirect(reverse('checksource:problemid',args=[problem_id]))	
		"""
		form = ImgProblemForm(request.POST,request.FILES)
		new_img = form.save(commit=False)
		new_img.Checkproblem = problem
		new_img.save()
		return HttpResponseRedirect(reverse('checksource:problemid',args=[problem_id]))
		"""
		
def deleteimg(request,img_id):
	next=request.GET.get('next','/')
	imgproblem = ImgProblem.objects.get(id = img_id)
	imgproblem.delete()
	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
	#return HttpResponseRedirect(reverse('checksource:allproblems'))	
	
def problemid(request,p_id):
	problem = Checkproblem.objects.get(id = p_id)
	i = set()
	for imgs in problem.imgproblem_set.all():
		i.add(imgs)
	context = {'pblm':problem,'imgproblem':i}
	return render(request, 'checksource/problemid.html', context)
	
def problemidcheck(request,p_id,checkwhenstart,checkwhenend,checkdepartment,checkway,checkwho,problemdetail,problemtype,problemsolve,whoresponsible,departmentincharge,problemdepartment,departmentwho,problemteam,problemwho,problemreason,projecttype,closewho,ifdone):
	pdic = ['p_id','checkwhenstart','checkwhenend','checkdepartment','checkway','checkwho','problemdetail','problemtype','problemsolve','whoresponsible','departmentincharge','problemdepartment','departmentwho','problemteam','problemwho','problemreason','projecttype','closewho']
	paramdic={}
	paramdic['checkwhenstart']= checkwhenstart
	paramdic['checkwhenend']=checkwhenend
	paramdic['checkdepartment']=checkdepartment
	paramdic['checkway']=checkway
	paramdic['checkwho']=checkwho
	paramdic['problemdetail']=problemdetail
	paramdic['problemtype']=problemtype
	paramdic['problemsolve']=problemsolve
	paramdic['whoresponsible']=whoresponsible
	paramdic['departmentincharge']=departmentincharge
	paramdic['problemdepartment']=problemdepartment
	paramdic['departmentwho']=departmentwho
	paramdic['problemteam']=problemteam
	paramdic['problemwho']=problemwho
	paramdic['problemreason']=problemreason
	paramdic['projecttype']=projecttype
	paramdic['closewho']=closewho
	paramdic['ifdone']=ifdone
	problem = Checkproblem.objects.get(id = p_id)
	
				
	i = set()
	for imgs in problem.imgproblem_set.all():
		i.add(imgs)
	context = {'pblm':problem,'imgproblem':i,'paramdic':paramdic}
	return render(request, 'checksource/problemidcheck.html', context)
	
	
def editproblemcheck(request,p_id,checkwhenstart,checkwhenend,checkdepartment,checkway,checkwho,problemdetail,problemtype,problemsolve,whoresponsible,departmentincharge,problemdepartment,departmentwho,problemteam,problemwho,problemreason,projecttype,closewho,ifdone):
	problem = Checkproblem.objects.get(id=p_id)
	paramdic={}
	paramdic['p_id']= p_id
	paramdic['checkwhenstart']= checkwhenstart
	paramdic['checkwhenend']=checkwhenend
	paramdic['checkdepartment']=checkdepartment
	paramdic['checkway']=checkway
	paramdic['checkwho']=checkwho
	paramdic['problemdetail']=problemdetail
	paramdic['problemtype']=problemtype
	paramdic['problemsolve']=problemsolve
	paramdic['whoresponsible']=whoresponsible
	paramdic['departmentincharge']=departmentincharge
	paramdic['problemdepartment']=problemdepartment
	paramdic['departmentwho']=departmentwho
	paramdic['problemteam']=problemteam
	paramdic['problemwho']=problemwho
	paramdic['problemreason']=problemreason
	paramdic['projecttype']=projecttype
	paramdic['closewho']=closewho
	paramdic['ifdone']=ifdone
	if request.method != 'POST':
		form = CheckproblemForm(instance=problem)
		context = {'pblm':problem,'form': form,'paramdic':paramdic}
		return render(request, 'checksource/editproblemcheck.html', context)
	else:
		form = CheckproblemForm(instance=problem, data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('checksource:problemidcheck',kwargs=paramdic))
			
def uploadcheck(request,p_id,checkwhenstart,checkwhenend,checkdepartment,checkway,checkwho,problemdetail,problemtype,problemsolve,whoresponsible,departmentincharge,problemdepartment,departmentwho,problemteam,problemwho,problemreason,projecttype,closewho,ifdone):
	
	problem = Checkproblem.objects.get(id=p_id)
	paramdic={}
	paramdic['p_id']= p_id
	paramdic['checkwhenstart']= checkwhenstart
	paramdic['checkwhenend']=checkwhenend
	paramdic['checkdepartment']=checkdepartment
	paramdic['checkway']=checkway
	paramdic['checkwho']=checkwho
	paramdic['problemdetail']=problemdetail
	paramdic['problemtype']=problemtype
	paramdic['problemsolve']=problemsolve
	paramdic['whoresponsible']=whoresponsible
	paramdic['departmentincharge']=departmentincharge

checksource/templates/checksource/base.html
{% load bootstrap3 %}
{% load staticfiles %}
 <!DOCTYPE html>
 <html lang="en">
 <head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
<title>吉林货运部风险源系统</title>
 {% bootstrap_css %}
{% bootstrap_javascript %}
{{ form.media }}
 </head>



<body>
<!-- Static navbar -->
 <nav class="navbar navbar-default navbar-static-top">
<div class="container">
<div class="navbar-header">
 <button type="button" class="navbar-toggle collapsed"
data-toggle="collapse" data-target="#navbar"
aria-expanded="false" aria-controls="navbar">
</button>
 <a class="navbar-brand" href="{% url 'checksource:index' %}">主页</a>
<a class="navbar-brand" href="{% url 'checksource:inquireinput' %}">查询</a>
<a class="navbar-brand" href="{% url 'checksource:newproblem' %}">添加</a>

</div>




<!--/.nav-collapse -->
</div>
</nav>

<div class="container-fluid">
<div class="page-header">
 {% block header %}{% endblock header %}
</div>
<div>
 {% block content %}{% endblock content %}
</div>
</div> <!-- /container -->

</body>
</html>

checksource/templates/checksource/editproblem.html
 {% extends "checksource/base.html" %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block header %}
<h2>修改问题的内容:</h2>
{% endblock header %}
{% block content %}
<form action="{% url 'checksource:editproblem' problem.id %}" method='post'>
{% csrf_token %}
{% bootstrap_form form %}
 {% buttons %}
<button name="submit" class="btn btn-primary">保存修改</button>
{% endbuttons %}
</form>
{% endblock content %}

checksource/templates/checksource/inquireinput.html
 {% extends "checksource/base.html" %}

{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{{ form.media }}

 {% block header %}
<h2>请输入查询条件：</h2>
{% endblock header %}

{% block content %}
 <form action="{% url 'checksource:inquireinput' %}" method='post'>
 {% csrf_token %}
{% bootstrap_form form %}    
 {% buttons %}
<button name="submit" class="btn btn-primary">提交</button>
{% endbuttons %}
</form>
{% endblock content %}

checksource/templates/checksource/problemid.html
 {% extends "checksource/base.html" %}
{% load bootstrap3 %}
{% load staticfiles %}
 {% block header %}
<h2>问题内容:</h2>
{% endblock header %}
 
{% block content %}
<table class="table table-bordered" id="tb" style='width:2200px;table-layout:fixed;'>
<th style='width:6%;'>检查日期</th>
        <th style='width:4%;'>检查部门</th>
        <th style='width:4%;'>检查方式</th>
        <th style='width:4%;'>检查者</th>
        <th style='width:9%;'>问题描述</th>
        <th style='width:3%;'>分类</th>
        <th style='width:9%;'>整改措施</th>
        <th style='width:6%;'>部分管责任人</th>
        <th style='width:5%;'>主控部门</th>
        <th style='width:5%;'>责任部门</th>
        <th style='width:4%;'>部门负责人</th>
        <th style='width:4%;'>责任班组</th>
        <th style='width:4%;'>具体责任人</th>
        <th style='width:9%;'>本部门原因分析</th>
        <th style='width:6%;'>预计关闭日期</th>
        <th style='width:4%;'>是否落实</th>
        <th style='width:4%;'>项目分类</th>
        <th style='width:4%;'>关闭批准人</th>
        <th style='width:3%;'>备注</th>      
    </tr>
    </thead>
    <tbody> 
    <tr>
        <td>{{pblm.checkwhen|default_if_none:""}}</td>
        <td>{{pblm.checkdepartment|default_if_none:""}}</td>
        <td>{{pblm.checkway|default_if_none:""}}</td>
        <td>{{pblm.checkwho|default_if_none:""}}</td>
        <td>{{pblm.problemdetail|default_if_none:""}}</td>
        <td>{{pblm.problemtype|default_if_none:""}}</td>
        <td>{{pblm.problemsolve|default_if_none:""}}</td>
        <td>{{pblm.whoresponsible|default_if_none:""}}</td>
        <td>{{pblm.departmentincharge|default_if_none:""}}</td>
        <td>{{pblm.problemdepartment|default_if_none:""}}</td>
        <td>{{pblm.departmentwho|default_if_none:""}}</td>
        <td>{{pblm.problemteam|default_if_none:""}}</td>
        <td>{{pblm.problemwho|default_if_none:""}}</td>
        <td>{{pblm.problemreason|default_if_none:""}}</td>
        <td>{{pblm.closedate|default_if_none:""}}</td>
        {% if pblm.ifdone %}
        <td bgcolor=green>
		{% else %}	
        <td bgcolor=red>
		{% endif%}	
			{% if pblm.ifdone%}是
			{%else%}否
			{%endif%}
		</td>
        <td>{{pblm.projecttype|default_if_none:""}}</td>
        <td>{{pblm.closewho|default_if_none:""}}</td>
        <td>{{pblm.somethingelse|default_if_none:""}}</td>
        <tr>
        <td colspan="19">
{% for i in imgproblem %}
{%if i.Checkproblem.id == pblm.id%}

<img src = '{{i.img.url}}' height="180px">
<a href="{% url 'checksource:deleteimg' i.id %}" onclick="return confirm('确定删除图片？')"><img class="del" src="/media/media/material/del.jpg" /></a>
{%endif%}	
{% endfor %}
</td></tr>

<tr>
<td colspan="19" height='50px'>

<a href="{% url 'checksource:editproblem' pblm.id %}"><button class="btn btn-primary">修改内容</button></a>
<a href="{% url 'checksource:upload' pblm.id %}"><button class="btn btn-primary">续传图片</button></a>
<a href="{% url 'checksource:problemdoneconfirmnew' p_id=pblm.id %}" onclick="return confirm('是否确定关闭此问题?\n\n请确认！')"><button class="btn btn-primary">整改确认</button></a>
<a href="{% url 'checksource:deleteproblem' p_id=pblm.id %}" onclick="return confirm('是否删除此问题?\n\n请确认！')"><button class="btn btn-danger">删除问题</button></a>

</td>	

</tr>

</tbody>

</table>
{% endblock content %} 